new-msg

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -78,16 +78,28 @@ jobs:
           fi
 
       - name: Merge pre-* into base branch
-        if: steps.base_branch.outputs.base_branch != 'none'
+        if: steps.check_running.outputs.skip == 'false'
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-          git fetch origin
-          git checkout ${{ steps.base_branch.outputs.base_branch }}
-          git merge origin/${GITHUB_REF##*/} --ff-only
-          git push origin ${{ steps.base_branch.outputs.base_branch }}
+         git config user.name "github-actions[bot]"
+         git config user.email "github-actions[bot]@users.noreply.github.com"
+    
+         git fetch origin
+
+         base_branch="${{ steps.base_branch.outputs.base_branch }}"
+         source_branch="${GITHUB_REF##*/}"
+
+         echo "Merging $source_branch into $base_branch"
+    
+         git checkout "$base_branch"
+         git merge origin/"$source_branch" --ff-only || {
+         echo "❌ Fast-forward merge not possible. Merge aborted."
+         exit 1
+         }
+
+         git push origin "$base_branch"
+
 
 # Other jobs like code_quality_check, quality, cypress_test, and revert_merge remain unchanged.
 
